apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tk95qgsvt-go 
  janus-idp.io/tekton: tk95qgsvt-go
  backstage.io/kubernetes-id: tk95qgsvt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tk95qgsvt-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  